// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNU_bo_diZDc6phGzrvD7oHn42B7UnYz0',
    appId: '1:542370963010:web:4d5f5f3102f4d3f0f797db',
    messagingSenderId: '542370963010',
    projectId: 'benawanghub',
    authDomain: 'benawanghub.firebaseapp.com',
    storageBucket: 'benawanghub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNn5o4v8ma8-pejARL4iQrQ7NH9FmaSdI',
    appId: '1:542370963010:android:b43cbd389487e914f797db',
    messagingSenderId: '542370963010',
    projectId: 'benawanghub',
    storageBucket: 'benawanghub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt96Q4YZrYwqwezlDOr4ojD-I-E96FV98',
    appId: '1:542370963010:ios:5bcd978550318908f797db',
    messagingSenderId: '542370963010',
    projectId: 'benawanghub',
    storageBucket: 'benawanghub.firebasestorage.app',
    iosBundleId: 'com.example.benawanghub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt96Q4YZrYwqwezlDOr4ojD-I-E96FV98',
    appId: '1:542370963010:ios:5bcd978550318908f797db',
    messagingSenderId: '542370963010',
    projectId: 'benawanghub',
    storageBucket: 'benawanghub.firebasestorage.app',
    iosBundleId: 'com.example.benawanghub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNU_bo_diZDc6phGzrvD7oHn42B7UnYz0',
    appId: '1:542370963010:web:9a2f9f8cc020578df797db',
    messagingSenderId: '542370963010',
    projectId: 'benawanghub',
    authDomain: 'benawanghub.firebaseapp.com',
    storageBucket: 'benawanghub.firebasestorage.app',
  );
}
